server.port=8080
spring.application.name=API-GATEWAY

# Eureka Server Address
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true

# --- ROUTE 1: ZOMATO SERVICE ---
spring.cloud.gateway.server.webflux.routes[0].id=zomato-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://ZOMATO-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/zomato/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1

# --- ROUTE 2: SWIGGY SERVICE ---
spring.cloud.gateway.server.webflux.routes[1].id=swiggy-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://SWIGGY-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/swiggy/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=1

# --- ROUTE 3: COMPARISON SERVICE ---
spring.cloud.gateway.server.webflux.routes[2].id=comparison-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://COMPARISON-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/compare/**

# Keep your logging level so you can verify the routing!
logging.level.org.springframework.cloud.gateway=DEBUG